### ISSUE TITLE
Bullet doesn't expand properly

### ISSUE THREAD

**Issue by tnrich** [rmnoon/WorkflowyList#1]
Hey there! 

Love you tool and love workflowy. I am super impressed that you got this to work, so big kudos! One thing that is holding me up from using your tool is this:

![image](https://cloud.githubusercontent.com/assets/2730609/24876993/8d8dc540-1de2-11e7-96ee-70d9b4258217.png)

vs

![image](https://cloud.githubusercontent.com/assets/2730609/24877059/c84f23fe-1de2-11e7-8d2b-df10c0492261.png)

As you can see the note doesn't look correct in your widget. Could you please fix that? Thanks!

**Comment by rmnoon** [comment]
Hi there,

I think you've actually got newlines in the title of your bullet (i.e. that's not a note).  Thus the app is kinda doing the right thing (except for the fact that the Android HTML renderer doesn't render newlines like your browser does... it's primarily for text formatting).

Here's what a note looks like in my browser:
![image](https://cloud.githubusercontent.com/assets/4371952/24884845/344fde5a-1e00-11e7-92a6-8a48b57cb84e.png)

and on the client:
![image](https://cloud.githubusercontent.com/assets/4371952/24885013/0fd4b2ca-1e01-11e7-8f5f-6ee1abfdac71.png)

**Comment by tnrich** [comment]
Hmmm interesting points. Okay, well I guess I was hoping to be able to have new lines displayed like they would display in the browser. But now that I am trying it in the browser I realize I'm not even able to make new lines in the title so maybe this is just a moot point. Thanks for getting back to me!

**Comment by rmnoon** [comment]
Kinda curious what your newlines actually are in workflowy... are they `\n`s or `<br />`s or what?  Any way you can look at the responses coming back in your browser and tell me what the JSON is?  It's unlikely that I can change the way that Android is rendering the text without hacking up their HTML renderer (which doesn't sound worth it).

If not, no worries.  I'm going to close this for now.
