### ISSUE TITLE
  Are you continuing developing this widget?

### ISSUE THREAD

**Issue by soraiyu** [rmnoon/WorkflowyList#2]
I found the tool "workflowy" this week. I think I want to use it by android widget.
I searched "android widget workflowy" by Google. Then, I found this repository. I'm happy.
But I can't find this widget on Google Play.

 Are you continuing developing this widget?

Thank you.

**Comment by rmnoon** [comment]
Hi there!  I pulled it from the Play Store because Workflowy changed the way authentication works (which I had to reverse engineer here) and I haven't had the time to fix it.  Feel free to submit a PR if you know Java and feel like analyzing your network tab in your browser. =)

**Comment by soraiyu** [comment]
I understand the reason. I try to analyze the way authentication and submit a PR if I can.
